name: publish

on:
  push:
    branches: [master]

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: yarn
      - name: Deploy
        run: yarn build
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: docs.top.gg
